# @package _group_
# (mgc, lf0, vuv, bap)
stream_sizes: [180, 3, 1, 15]
has_dynamic_features: [true, true, false, true]
num_windows: 3
# If None, automatically set based on stream sizes
stream_weights:

netG:
  _target_: nnsvs.model.RMDN
  in_dim: 424
  out_dim: 199
  hidden_dim: 256
  num_layers: 2
  dropout: 0.1
  bidirectional: true
  num_gaussians: 2
